image: "node:latest"

stages:
    - test

test:
    stage: test
    script:
        - yarn install
        - yarn run lint
        - yarn run test
        - yarn global add @mapbox/geojsonhint
        - yarn run test-e2e
    artifacts:
        name: "nsw-rfs-majorincidents"
        paths:
            - nsw-rfs-majorincidents.geojson
            - nsw-rfs-majorincidents-avoidgeometrycollections.geojson
            - nsw-rfs-majorincidents-avoidslivers.geojson
