image: "node:latest"

stages:
    - test

test:
    stage: test
    script:
        - yarn install
        - yarn run lint
        - yarn run test
        - yarn global add geojsonhint
        - yarn run geojsonhint
    artifacts:
        name: "nsw-rfs-majorincidents"
        paths:
            - nsw-rfs-majorincidents.geojson
